[[OpenSWPC]]
arch = "aarch64"
git-tree-sha1 = "ab4a99f71158542b2dd976fa7fe089885e1e7866"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[OpenSWPC.download]]
    sha256 = "353cc54279a4e17c10850d30a79c613264c8d697d4a39f9ee42da04f98afa64a"
    url = "https://github.com/boriskaus/OpenSWPC_jll.jl/releases/download/OpenSWPC-v26.9.1+0/OpenSWPC.v26.9.1.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[OpenSWPC]]
arch = "x86_64"
git-tree-sha1 = "b59bb10f897e82ee00b19dfc047653cb36bf2fbd"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[OpenSWPC.download]]
    sha256 = "40168460e71379cf4830ea625584872797c2f46b2a0f2196b72b3bafd572334a"
    url = "https://github.com/boriskaus/OpenSWPC_jll.jl/releases/download/OpenSWPC-v26.9.1+0/OpenSWPC.v26.9.1.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[OpenSWPC]]
arch = "x86_64"
git-tree-sha1 = "16c29379c7a07239e29da61213f6efb66be40588"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[OpenSWPC.download]]
    sha256 = "b71549bb69f5c42a3cc1c1026ba208310a398b256a9005831db92dabd70f5260"
    url = "https://github.com/boriskaus/OpenSWPC_jll.jl/releases/download/OpenSWPC-v26.9.1+0/OpenSWPC.v26.9.1.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[OpenSWPC]]
arch = "x86_64"
git-tree-sha1 = "d124e38ad1155ed7d9a4dcd6789add951042b068"
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[OpenSWPC.download]]
    sha256 = "c2621e2819fa3dae9d8f6cb56f84393d765e4631a85e95d0f5597d3121fd2778"
    url = "https://github.com/boriskaus/OpenSWPC_jll.jl/releases/download/OpenSWPC-v26.9.1+0/OpenSWPC.v26.9.1.x86_64-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
