[[OpenSWPC]]
arch = "aarch64"
git-tree-sha1 = "69cdd7648f65dd4dc4fb509073ad2c97a81b24df"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[OpenSWPC.download]]
    sha256 = "0bb55269ee9560c1b433760354659f5349a11e01d84de1ddc618bf1208ef3ff5"
    url = "https://github.com/boriskaus/OpenSWPC_jll.jl/releases/download/OpenSWPC-v26.9.1+0/OpenSWPC.v26.9.1.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[OpenSWPC]]
arch = "x86_64"
git-tree-sha1 = "cbf937c51657da804576fe1ab61a8efd47a79de7"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[OpenSWPC.download]]
    sha256 = "ec09a783f44a62c6e8d9539ea05c282563e399811b5c44de4fa2a189a10b2b02"
    url = "https://github.com/boriskaus/OpenSWPC_jll.jl/releases/download/OpenSWPC-v26.9.1+0/OpenSWPC.v26.9.1.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[OpenSWPC]]
arch = "x86_64"
git-tree-sha1 = "5525f8d4fffe7e89b183c61939bf3352591ac559"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[OpenSWPC.download]]
    sha256 = "947708c8270b8fad6b808ae837e501321fb3ebdfe809e7637cf4786cb5623cf2"
    url = "https://github.com/boriskaus/OpenSWPC_jll.jl/releases/download/OpenSWPC-v26.9.1+0/OpenSWPC.v26.9.1.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[OpenSWPC]]
arch = "x86_64"
git-tree-sha1 = "eaed32bb030a836a0ec9417dc3add7ad3d092b83"
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[OpenSWPC.download]]
    sha256 = "130bca29b776c6289cdec1ab3bf18ab86519efe4a5b70e32e9e00cdf5815058b"
    url = "https://github.com/boriskaus/OpenSWPC_jll.jl/releases/download/OpenSWPC-v26.9.1+0/OpenSWPC.v26.9.1.x86_64-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
