# Autogenerated wrapper script for OpenSWPC_jll for aarch64-apple-darwin-libgfortran5-mpi+mpich
export swpc_3d

using CompilerSupportLibraries_jll
using NetCDFF_jll
using NetCDF_jll
JLLWrappers.@generate_wrapper_header("OpenSWPC")
JLLWrappers.@declare_executable_product(swpc_3d)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, NetCDFF_jll, NetCDF_jll)
    JLLWrappers.@init_executable_product(
        swpc_3d,
        "bin/swpc_3d",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
