# Autogenerated wrapper script for OpenSWPC_jll for x86_64-linux-gnu-libgfortran5-mpi+mpich
export diff_snp, fdmcond, fs2grd, gen_rmed3d, grdsnp, ll2xy, mapregion, qmodel_tau, read_snp, swpc_3d, swpc_psv, swpc_sh, wvconv, xy2ll

using NetCDF_jll
using NetCDFF_jll
using CompilerSupportLibraries_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("OpenSWPC")
JLLWrappers.@declare_executable_product(diff_snp)
JLLWrappers.@declare_executable_product(fdmcond)
JLLWrappers.@declare_executable_product(fs2grd)
JLLWrappers.@declare_executable_product(gen_rmed3d)
JLLWrappers.@declare_executable_product(grdsnp)
JLLWrappers.@declare_executable_product(ll2xy)
JLLWrappers.@declare_executable_product(mapregion)
JLLWrappers.@declare_executable_product(qmodel_tau)
JLLWrappers.@declare_executable_product(read_snp)
JLLWrappers.@declare_executable_product(swpc_3d)
JLLWrappers.@declare_executable_product(swpc_psv)
JLLWrappers.@declare_executable_product(swpc_sh)
JLLWrappers.@declare_executable_product(wvconv)
JLLWrappers.@declare_executable_product(xy2ll)
function __init__()
    JLLWrappers.@generate_init_header(NetCDF_jll, NetCDFF_jll, CompilerSupportLibraries_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_executable_product(
        diff_snp,
        "bin/diff_snp",
    )

    JLLWrappers.@init_executable_product(
        fdmcond,
        "bin/fdmcond",
    )

    JLLWrappers.@init_executable_product(
        fs2grd,
        "bin/fs2grd",
    )

    JLLWrappers.@init_executable_product(
        gen_rmed3d,
        "bin/gen_rmed3d",
    )

    JLLWrappers.@init_executable_product(
        grdsnp,
        "bin/grdsnp",
    )

    JLLWrappers.@init_executable_product(
        ll2xy,
        "bin/ll2xy",
    )

    JLLWrappers.@init_executable_product(
        mapregion,
        "bin/mapregion",
    )

    JLLWrappers.@init_executable_product(
        qmodel_tau,
        "bin/qmodel_tau",
    )

    JLLWrappers.@init_executable_product(
        read_snp,
        "bin/read_snp",
    )

    JLLWrappers.@init_executable_product(
        swpc_3d,
        "bin/swpc_3d",
    )

    JLLWrappers.@init_executable_product(
        swpc_psv,
        "bin/swpc_psv",
    )

    JLLWrappers.@init_executable_product(
        swpc_sh,
        "bin/swpc_sh",
    )

    JLLWrappers.@init_executable_product(
        wvconv,
        "bin/wvconv",
    )

    JLLWrappers.@init_executable_product(
        xy2ll,
        "bin/xy2ll",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
